server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/grafana_autobuilder
    username: grafana_user
    password: sharvil39
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: sharvildhumal2023@gmail.com
    password: mrit yenj lbpo zmhm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

app:
  frontendBaseUrl: http://localhost:4200
  backendBaseUrl: http://localhost:8080
  jwt:
    secret: Y3hqdmJ1aXkxMjNiIUBhc2RqbmdvdWIlakJkZmdkc2l1YWJkaWg7YiNAIW9ibzt1ZHN2YmRzdnNkb2JzZGdm # BASE64 encoded secret
    expiration-ms: 3600000 # 1 hour

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.example.grafanaautobuilder: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

grafana:
  url: http://localhost:3000
  apiKey: glsa_fM7dnmH1K0ODHzeANHjou9PMDodHgYBF_6908361e
  # Set these so newly created panels default to your PostgreSQL datasource
  # Find the UID in Grafana: Configuration > Data sources > select your datasource > copy UID from the page URL or settings
  defaultDatasourceUid: fev06aq8frhfka
  defaultDatasourceType: postgres

supabase:
  url: ${SUPABASE_URL:https://byruaypxgnylkurmppqs.supabase.co}
  serviceKey: ${SUPABASE_SERVICE_KEY:}
  storage:
    bucket: ${SUPABASE_BUCKET:uploads}
