server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grafana_autobuilder
    username: grafana_user
    password: strong_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # In production, use Flyway and set this to 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.example.com # Replace with your SMTP server
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
          debug: true # Disable in production

app:
  frontendBaseUrl: http://localhost:4200
  backendBaseUrl: http://localhost:8080
  jwt:
    secret: cxjvbuiy123b!@asdjngoub%jbdfgbdsiuabdih;b#@!obo;udsvbdsvsdobsdgf # Set this as environment variable
    expiration-ms: 3600000 # 1 hour

logging:
  level:
    org.springframework: INFO
    com.example.grafanaautobuilder: DEBUG